headers:
  MyHeader: MyHeaderValue

metrics:
  - name: subnet_statistics
    type: object
    help: DHCP statistics of MoJO subnets
    path: '{ $.sites[*].*.subnets[*] }' 
    labels:
      cidr: '{ .cidr }'
      usage: '{ .usage }'
    values:
      remaining_ips: '{ .remaining_ips }'
      reservations_count: '{ .reservations_count }'

  - name: MoJO_site
    type: object
    help: CIDR Ranges present at MoJO sites
    path: '{ $.sites[*] }' 
    labels:
      Info: '{ }'
      subnets: '{ .*.subnets[*].cidr }'
    values:
      info: 1
      
      
    

