headers:
  MyHeader: MyHeaderValue
http_client_config:
  tls_config:
    insecure_skip_verify: true
  basic_auth:
    username: prometheus
    password: prometheus  ## Remember this is a SANDBOX! Always store secrets securely

metrics:
  - name: subnet_statistics
    type: object
    help: DHCP statistics of MoJO subnets
    path: '{ $.sites[*].*.subnets[*] }' 
    labels:
      cidr: '{ .cidr }'
    values:
      remaining_ips: '{ .remaining_ips }'
      reservations_count: '{ .reservations_count }'
      usage: '{ .usage }'

  - name: MoJO_site
    type: object
    help: CIDR Ranges present at MoJO sites
    path: '{ $.sites[*] }' 
    labels:
      Info: '{ }'
      subnets: '{ .*.subnets[*].cidr }'
    values:
      info: 1
      
      
    

