{
 "title": "DHCP Stats",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "SiteName", "label": "MoJO Site Name", "query": { "query": "MoJO_site_info" } },
   { "name": "Subnets", "query": { "query": "MoJO_site_info" } }
  ]
 },
 "panels": [
  {
   "title": "Site for $Subnets",
   "type": "table",
   "gridPos": { "h": 2, "w": 17, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "MoJO_site_info{Info=~\".+$Subnets.+\"} ",
     "legendFormat": "{{SiteName}}"
    }
   ]
  },
  {
   "title": "Subnets for $SiteName",
   "type": "table",
   "gridPos": { "h": 2, "w": 17, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "MoJO_site_info{Info=~\".+$SiteName.+\"} ",
     "legendFormat": "{{SiteName}}"
    }
   ]
  },
  {
   "title": "Subnet Usage by CIDR",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 17, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "subnet_statistics_usage", "legendFormat": "{{cidr}}" }
   ]
  }
 ]
}